version: '3'
services:
  webapp:
    build: 
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
  monitor:
    build: 
      context: ./web
    ports:
      - 80:80
    volumes:
      - .:/app
  orchestrator:
    build: 
      context: ./orch
    ports:
      - 8082:8080
    volumes:
      - .:/app
