#!./venv/bin/python
import jinja2
import time
import yaml
import subprocess
import sys
import re
import datetime
import math
import requests

server_ip = 'http://192.168.56.20:8080'
orch_ip = 'http://192.168.56.20:8082'
logfile = '/var/log/nginx/mysite.access.log'
conffile = '/etc/nginx/conf.d/custom.conf'
subprocess.run(['nginx'])

while True:
  data = requests.get(orch_ip + '/data')
  data = data.json()
  ip_list = data.keys()
  templateLoader = jinja2.FileSystemLoader(searchpath="./")
  templateEnv = jinja2.Environment(loader=templateLoader)
  TEMPLATE_FILE = "nginx.conf.jinja"
  template = templateEnv.get_template(TEMPLATE_FILE)
  outputText = template.render(ip_list=ip_list, server_ip=server_ip)
  print(outputText)
  with open(conffile, 'w') as fp:
    fp.write(outputText)
  # subprocess.run(['./docr', 'monitor_monitor_1'])
  subprocess.run(['nginx', '-t'])
  subprocess.run(['nginx', '-s', 'reload'])
  time.sleep(10)

  fp = open(logfile, "r+")
  ips = []
  strptime = datetime.datetime.strptime

  for text in fp.readlines():
      text = text.rstrip()
      found = re.findall(r'(?:[\d]{1,3})\.(?:[\d]{1,3})\.(?:[\d]{1,3})\.(?:[\d]{1,3})',text)
      match = text.partition('[')[-1].rpartition(']')[0]

      if found and match:
          s = match.split()
          d = time.mktime(datetime.datetime.strptime(s[0], "%d/%b/%Y:%H:%M:%S").timetuple())
          ips.append({'ipAddress': found[0], 'timestamp': math.ceil(d)})
  fp.truncate(0)
  print(ips)

  requests.post(orch_ip + '/data', json=ips)
